# Generated by Django 5.1.15 on 2026-07-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contactmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyviewed',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recentlyviewed',
            name='content_type',
            field=models.CharField(choices=[('resource', 'Resource'), ('article', 'Article'), ('scheme', 'Government Scheme'), ('recommendations', 'Recommendations Page'), ('search', 'Search Action')], max_length=20),
        ),
    ]
