import re
import json
import logging

logger = logging.getLogger(__name__)


class ResponseParser:
    """
    Utility class to parse, clean, and format responses generated by AI models.
    """

    @staticmethod
    def clean_markdown_wrappers(text: str) -> str:
        """
        Strips markdown delimiters like ```json ... ``` or ``` ... ```
        to isolate the raw payload text.
        """
        cleaned = text.strip()
        # Look for markdown code blocks
        match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", cleaned)
        if match:
            return match.group(1).strip()
        return cleaned

    @staticmethod
    def to_dict(text: str) -> dict:
        """
        Attempts to parse LLM text output into a python dictionary.
        Returns a dictionary wrapping the raw text under 'raw_response' if JSON decoding fails.
        """
        cleaned = ResponseParser.clean_markdown_wrappers(text)
        try:
            return json.loads(cleaned)
        except json.JSONDecodeError as exc:
            logger.debug(f"Failed to decode text as JSON, returning raw text wrap: {exc}")
            return {"response": text}
